language: node_js
node_js: stable

cache:
    apt: true
    directories:
        - node_modules

before_install:
    - export TZ='Asia/Shanghai'
    - npm install hexo-cli -g

install:
  - npm install

script:
  - hexo clean
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "andylizf"
  - git config user.email "andylizf@outlook.com"
  - git add .
  - git commit -m "Travis CI Auto Builder"
  - git push --force --quiet --set-upstream https://${GH_TOKEN}@github.com/andylizf/andylizf.github.io master

branches:
  only:
    - master