language: node_js
node_js: stable

cache:
    apt: true
    directories:
        - node_modules

before_install:
    - export TZ='Asia/Shanghai'
    - npm install hexo-cli -g
    - sed -i "s/github_token/${GH_TOKEN}/g" _config.yml || exit 1

install:
  - npm install
  - npm install hexo-deployer-git --save

script:
  - hexo clean
  - hexo g

after_success:
  - hexo deploy